version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    command: bash -c "rm -f tmp/pids/server.pid && rails s -p 80 -b 0.0.0.0"
    working_dir: /app
    container_name: compass_app
    hostname: app
    ports:
     - "80:80"
    expose:
      - 3000
    volumes:
      - ".:/app"
      - bundle_install:/bundle
    links:
      - postgres
    tty: true
    stdin_open: true

  postgres:
    image: postgres
    container_name: compass_postgres
    hostname: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres
    volumes:
      - postgres-data:/var/lib/postgres

  pgweb:
    container_name: compass_pgweb
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    links:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/compass_development?sslmode=disable
    depends_on:
      - postgres

volumes:
  postgres-data:
    driver: local
  bundle_install:
    driver: local
  node_modules:
    driver: local
